name: Build and Push Docker images

on:
  push:
    branches: [ "master" ]   # dispara no push da branch master
  workflow_dispatch:        # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # necessário para publicar no GHCR

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set repository name lowercase
        id: repo
        run: echo "repo_lower=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push chat-server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.repo_lower }}/chat-server:latest
            ghcr.io/${{ steps.repo.outputs.repo_lower }}/chat-server:${{ github.sha }}

      - name: Build and push chat-client
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./client/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.repo_lower }}/chat-client:latest
            ghcr.io/${{ steps.repo.outputs.repo_lower }}/chat-client:${{ github.sha }}
